=== VictorSIOESUPEC/LaboratoireLBC/LBC/ppe.dtd
<!-- dÃ©but de la DTD -->
<!-- DTD pour le stock initial du PPE -->
<!ELEMENT Stock (annee , code+) >
<!ELEMENT annee (#PCDATA) >
<!ELEMENT code (nom, quantite)>
<!ATTLIST code  code CDATA #REQUIRED>
<!ELEMENT nom (#PCDATA) >
<!ELEMENT quantite (#PCDATA) >

=== VictorSIOESUPEC/LaboratoireLBC/LBC/ppe(exemple).xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Stock SYSTEM "ppe.dtd">
<Stock>
<annee>2019</annee>
<code code = "1">
<nom>Augmentin</nom>
<quantite>10</quantite>
</code>

<code code = "2">
<nom>augmentin</nom>
<quantite>20</quantite>


</code>
</Stock>
